export enum ActionType {
 
  CHANGE_APP_LANGUAGE="CHANGE_APP_LANGUAGE",
  CHANGE_APP_THEME="CHANGE_APP_THEME",
  CHANGE_APP_DIRECTION="CHANGE_APP_DIRECTION",
  SET_APP_SETTINGS="SET_APP_SETTINGS",
  SET_FORCE_UPDATE="SET_FORCE_UPDATE",
  SET_GUSTER_ID="SET_GUSTER_ID",
  SAVE_USER_DATA="SAVE_USER_DATA",
  USER_LOGIN="USER_LOGIN",
  USER_LOGOUT="USER_LOGOUT",
    SET_FCM_TOKEN="SET_FCM_TOKEN"
}
