export default {
    //TabBarText
    "Notifications":"الاشعارات",
    "Opinion poll":"استطلاع رأي",
    "Home":"الرئيسية",
    "More":"المزيد",
    //HomeText
    "hometext1":"بورصة اسعار الورق اليومية",
    "Share":"مشاركة",
    "LE":"ج",
     //PollText
    "Votes":"صوت",
     //MoreText
     "MoreText1":"مرحبا بك في سوق المكتبات",
     'Sign in':"تسجيل الدخول",
     "Contact us":"تواصل معنا",
     "Shar":"دعوة الاصدقاء",
     //Loginin
     "Pass":"تخطي",
     "signin1":"سجل دخولك الان",
     "username":"اسم المستخدم",
     "usernamew":"اكتب اسم المستخدم",
     "pasword":"كلمة السر",
     "paswordw":"ادخل كلمة السر",
     "Forget password ?": "هل نسيت كلمة المرور؟",
"Don't have account": "ليس لديك حساب ؟",
"Sign up": "سجل الان",
//contactus
"contactus":"تواصل معنا",
"fullname":"الاسم",
"fullnamew":"اكتب الاسم",
"Email":"الايميل",
"Emailw":"اكتب الايميل",
"message":"رسالتك",
"messagew":"اكتب رسالتك هنا",
"Send":"ارسال",
"message1":"معلومات التواصل معنا",
//Signup
'Choose City':"اختار المحافظة",
"signtxt1":"انشاء حساب جديد",
"adress":"العنوان",
"adressw":"اكتب العنوان",
"Government":"المحافظة",
"Governmentw":"اختار المحافظة",
"AccountType":"نوع الحساب",
"AccountTypew":"اختار نوع الحساب",
"confirmpasword":"تاكيد كلمة السر",
"confirmpaswordw":"تاكيد كلمة السر",
"Phone":"رقم التليفون",
"Phonew":"اكتب رقم التليفون",
'Address is Required':"العنوان مطلوب",
'Fullname is required':"الاسم الكامل مطلوب",
'Address is Required':"العنوان مطلوب",
'Email is required':"البريد الإلكتروني مطلوب",
'Passwords must match':"يجب أن تتطابق كلمات المرور",
'Password is Required':"كلمة المرور مطلوبة",
'ConfirmPassword is Required':"تأكيد كلمة المرور مطلوب",
'Mobile Number is Required':"رقم الهاتف المحمول مطلوب",
'It must be numbers and 11 digits':"يجب أن يكون أرقامًا و11 رقمًا",
"mobilenumber must be at least 11 characters":"يجب أن يكون أرقامًا و11 رقمًا",
"Choose Account Type":"اختار نوع الحساب",
"You must pick a role!":"عليك أن تختار دوراً!",
"You must pick a city!":"يجب عليك اختيار مدينة!",
"Email must be a valid email":"يجب أن يكون البريد الإلكتروني صالحًا",
 "Password must be at least 6 characters":"يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
 "Fail Passwords must be at least 6 characters.Passwords must have at least one digit ('0'-'9').":" يجب أن تحتوي كلمات المرور على 6 أحرف على الأقل. يجب أن تحتوي كلمات المرور على رقم واحد على الأقل (من '0' إلى '9').",
//forcetxt
"forcetitle":"تحديث التطبيق",
"forceMessage":"يوجد بعض المميزات والتحديثات الجديدة يجب عليك تحديث التطبيق ",
"forcetxt1":"تحديث الان",
"forcetxt2":"ربما لاحقا",
"Something Went wrong":"حدث خطأ ما"
};
