export default {
    //TabBarText
    "Notifications": "الاشعارات",
    "Opinion poll": "استطلاع رأي",
    "Home": "الرئيسية",
    "More": "المزيد",
    //HomeText
    "hometext1": "بورصة اسعار الورق اليومية",
    "Share": "مشاركة",
    "LE": "ج",
    //PollText
    "Votes": "صوت",
    //MoreText
    "MoreText1": "مرحبا بك في سوق المكتبات",
    'Sign in': "تسجيل الدخول",
    "Contact us": "تواصل معنا",
    "Shar": "دعوة الاصدقاء",
    //Loginin
    "Pass": "تخطي",
    "signin1": "سجل دخولك الان",
    "username": "اسم المستخدم",
    "usernamew": "اكتب اسم المستخدم",
    "pasword": "كلمة السر*",
    "paswordw": "ادخل كلمة السر",
    "Forget password ?": "هل نسيت كلمة المرور؟",
    "Don't have account": "ليس لديك حساب ؟",
    "Sign up": "سجل الان",
    //contactus
    "contactus": "تواصل معنا",
    "fullname": "اسم المستخدم*",
    "fullnamew": "اكتب اسم المستخدم",
    "Email": "البريد الالكتروني*",
    "Emailw": "اكتب البريد الالكتروني",
    "message": "رسالتك",
    "messagew": "اكتب رسالتك/اقتراحك هنا",
    "Send": "ارسال",
    "message1": "معلومات التواصل معنا",
    'message is Required': "يجب إدخال الرسالة",
    "Full Name must be at least 2 characters": "يجب أن يتكون الاسم الكامل من حرفين على الأقل",
    "Message sent successfully": "تم إرسال الرسالة بنجاح",
    //Signup
    'Choose City': "اختار المحافظة",
    "signtxt1": "انشاء حساب جديد",

    'Address is Required': "العنوان مطلوب",
    'Fullname is required': "الاسم الكامل مطلوب",
    'Address is Required': "العنوان مطلوب",
    'Email is required': "البريد الإلكتروني مطلوب",
    'Passwords must match': "يجب أن تتطابق كلمات المرور",
    'Password is Required': "كلمة المرور مطلوبة",
    'ConfirmPassword is Required': "تأكيد كلمة المرور مطلوب",
    'Mobile Number is Required': "رقم الهاتف المحمول مطلوب",
    'It must be numbers and 11 digits': "يجب أن يكون أرقامًا و11 رقمًا",
    "mobilenumber must be at least 11 characters": "يجب أن يكون أرقامًا و11 رقمًا",
    "Choose Account Type": "اختار نوع الحساب",
    "You must pick a role!": "عليك أن تختار دوراً!",
    "You must pick a city!": "يجب عليك اختيار مدينة!",
    "Email must be a valid email": "يجب أن يكون البريد الإلكتروني صالحًا",
    "Password must be at least 6 characters": "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل",
    "Fail Passwords must be at least 6 characters.Passwords must have at least one digit ('0'-'9').": " يجب أن تحتوي كلمات المرور على 6 أحرف على الأقل. يجب أن تحتوي كلمات المرور على رقم واحد على الأقل (من '0' إلى '9').",
    "signtxthint1": "من فضلك أدخل بريدك الإلكتروني، وسنرسل لك رمز التحقق عبر البريد الالكتروني.",
    "Next": "التالي",
    "Do you have account": " لديك حساب ؟",
    "Agree on":"اوفق علي",
    "Privcy and terms":"الشروط والاحكام",
    "You must agree on terms":"يجب أن توافق على الشروط",
    "Some Fields has incorrect Values!":"بعض الحقول تحتوي على قيم غير صحيحة!",
     "The Name field is required.": "حقل الاسم مطلوب.",
  "The Email field is required.": "حقل البريد الإلكتروني مطلوب.",
  "The Password field is required.": "حقل كلمة المرور مطلوب.",
  "The Addresses field is required.": "حقل العنوان مطلوب.",
  "The PhoneNumber field is required.": "حقل رقم الهاتف مطلوب.",
    //ConfirmationCode
    "contxthint1": "سوف يتم إرسال رمز تحقق مكوّن من 4 أرقام خلال دقيقتين إلى البريد الإلكتروني example@email.com",
    "confirmtxt1": "رمز التحقق",
    "confirmtxt2": "ادخل رمز التحقق",
    "VerificationCode is required": "يجب أدخال كود التفعيل",
    "VerificationCode must be at least 4 characters": "كود التفعيل يجب ان يكون على الأقل 4 أرقام",
    "confirmtxt3": "لم يتم إرسال الكود؟",
    "confirmtxt4": "أعد الإرسال",
    //RegistertionForm
    "regtxt1": "البيانات الشخصية",
    "Phone": "رقم التليفون*",
    "Phonew": "ادخل رقم التليفون",
    "regtxt2":"كمل بياناتك",
        "adress": "العنوان",
    "adressw": "اكتب العنوان",
    "Government": "المحافظة*",
    "Governmentw": "اختار المحافظة",
    "AccountType": "نوع الحساب*",
    "AccountTypew": "اختار نوع الحساب",
    "confirmpasword": "تاكيد كلمة السر*",
    "confirmpaswordw": "تاكيد كلمة السر",
    "Area":"المنطقة*",
    "Areaw":"اختار المنطقة",
    "Market":"الأسواق التي تهمك *",
    "Marketw":"اختر الأسواق التي تهمك",
    "otherPhoneNumber":"رقم التليفون اخر",
    "otherPhoneNumberw":"ادخل رقم التليفون اخر",
    'Choose Area':"اختر المنطقة",
    "You must pick a area!":"يجب عليك اختيار منطقة",
    'Save':"حفظ",
    "VerificationCode must contain only letters (Arabic or English)":"يجب أن يحتوي رمز التحقق على أحرف فقط (العربية أو الإنجليزية)",
    "SelectToolsw":"اكتب الادوات المتاحة",
    "You must choose a market!":"يجب عليك اختيار السوق!",
    "Activity is required":"النشاط مطلوب",
    //forcetxt
    "forcetitle": "تحديث التطبيق",
    "forceMessage": "يوجد بعض المميزات والتحديثات الجديدة يجب عليك تحديث التطبيق ",
    "forcetxt1": "تحديث الان",
    "forcetxt2": "ربما لاحقا",
    "Something Went wrong": "حدث خطأ ما",
    "GM": "جم",
};
