export default {
  //TabBarText
  Notifications: 'Notifications',
  'Opinion poll': 'Opinion poll',
  Home: 'Home',
  More: 'More',
  //HomeText
  hometext1: 'Daily Paper Price Exchange',
  Share: 'Share',
  LE: 'LE',
  //PollText
  Votes: 'Votes',
  //MoreText
  MoreText1: 'Welcome to Bookstores Market',
  'Sign in': 'Sign in',
  'Contact us': 'Contact us',
  Shar: 'Invite Friends',
  //Loginin
  Pass: 'Skip',
  signin1: 'Sign in now',
  username: 'Email or Phone Number*',
  usernamew: 'Enter email or phone number',
  pasword: 'Password*',
  paswordw: 'Enter password',
  'Forget password ?': 'Forget password?',
  "Don't have account": "Don't have an account?",
  'Sign up': 'Sign up now',
  //contactus
  contactus: 'Contact us',
  fullname: 'Username*',
  fullnamew: 'Enter username',
  Email: 'Email*',
  Emailw: 'Enter email',
  message: 'Your message',
  messagew: 'Write your message/suggestion here',
  Send: 'Send',
  message1: 'Contact information',
  'message is Required': 'Message is required',
  'Full Name must be at least 2 characters':
    'Full name must be at least 2 characters',
  'Message sent successfully': 'Message sent successfully',
  //Signup
  'Choose City': 'Choose Governorate',
  signtxt1: 'Create new account',
  signtxt2: 'Forget password',
  signtxt3: 'Change password',
  'Address is Required': 'Address is required',
  'Fullname is required': 'Full name is required',
  'Email is required': 'Email is required',
  'Passwords must match': 'Passwords must match',
  'Password is Required': 'Password is required',
  'NewPassword is required': 'New Password is required',
  'ConfirmPassword is Required': 'Confirm password is required',
  'Mobile Number is Required': 'Mobile number is required',
  'It must be numbers and 11 digits': 'Must be numbers and 11 digits',
  'mobilenumber must be at least 11 characters':
    'Must be numbers and 11 digits',
  'Choose Account Type': 'Choose account type',
  'You must pick a role!': 'You must pick a role!',
  'You must pick a city!': 'You must pick a city!',
  'Email must be a valid email': 'Email must be a valid email',
  'Password must be at least 6 characters':
    'Password must be at least 6 characters',
  "Fail Passwords must be at least 6 characters.Passwords must have at least one digit ('0'-'9').":
    "Passwords must be at least 6 characters. Passwords must have at least one digit ('0'-'9').",
  signtxthint1:
    'Please enter your email, and we will send you a verification code via email.',
  Next: 'Next',
  'Do you have account': 'Do you have an account?',
  'Agree on': 'I agree on',
  'Privcy and terms': 'Privacy and terms',
  'You must agree on terms': 'You must agree on terms',
  'Some Fields has incorrect Values!': 'Some fields have incorrect values!',
  'The Name field is required.': 'The name field is required.',
  'The Email field is required.': 'The email field is required.',
  'The Password field is required.': 'The password field is required.',
  'The Addresses field is required.': 'The address field is required.',
  'The PhoneNumber field is required.': 'The phone number field is required.',
  //ConfirmationCode
  contxthint1:
    'A 4-digit verification code will be sent within 2 minutes to your email',
  confirmtxt1: 'Verification Code',
  confirmtxt2: 'Enter verification code',
  'VerificationCode is required': 'Verification code is required',
  'VerificationCode must be at least 4 characters':
    'Verification code must be at least 4 digits',
  confirmtxt3: "Didn't receive the code?",
  confirmtxt4: 'Resend',
  //RegistertionForm
  regtxt1: 'Personal Information',
  Phone: 'Phone Number*',
  Phonew: 'Enter phone number',
  regtxt2: 'Complete your data',
  adress: 'Address*',
  adressw: 'Enter address',
  Government: 'Governorate*',
  Governmentw: 'Choose governorate',
  AccountType: 'Account Type*',
  AccountTypew: 'Choose account type',
  confirmpasword: 'Confirm Password*',
  confirmpaswordw: 'Confirm password',
  Area: 'Area*',
  Areaw: 'Choose area',
  Market: 'Markets of interest *',
  Marketw: 'Choose markets of interest',
  otherPhoneNumber: 'Other phone number',
  otherPhoneNumberw: 'Enter other phone number',
  'Choose Area': 'Choose area',
  'You must pick a area!': 'You must pick an area',
  Save: 'Save',
  'VerificationCode must contain only letters (Arabic or English)':
    'Verification code must contain only letters (Arabic or English)',
  SelectToolsw: 'Enter company services',
  'You must choose a market!': 'You must choose an activity!',
  'Activity is required': 'Activity is required',
  regtxt3: 'Work Information',
  input1: 'Company logo',
  CompanyName: 'Company Name*',
  CompanyNamew: 'Enter company name',
  Tools: 'Company Services*',
  Toolsww: 'Company Services',
  Toolsw: 'Choose company services',
  Actvity: 'Company Activity*',
  Actvityww: 'Company Activity',
  Actvityw: 'Choose company activity',
  redestratincom: 'Commercial Registration',
  addImage: 'Add images',
  Description: 'Brief Description*',
  Descriptionw:
    'Write a brief description such as specialized in high-quality printing and writing paper',
  payments: 'Payment Methods*',
  paymentsww: 'Payment Methods',
  paymentsw: 'Choose payment methods',
  toolswww: 'Enter company services',
  marketwwww: 'Enter markets of interest',
  Filter: 'Filter',
  Camera: 'Camera',
  Photos: 'Photos',
  'Image is required': 'Image is required',
  'You must pick a tools!': 'You must pick tools!',
  'You must choose  payments methods!': 'You must choose payment methods!',
  'CompanyName is required': 'Company name is required',
  regtxt4: 'Branches',
  regtxt5: 'Add another branch',
  regtxt6: 'Other phone numbers',
  regtxt7: 'Add another number',
  regtxt8: 'Your account has been created successfully',
  inputimg1: 'Profile picture',
  //forcetxt
  forcetitle: 'App Update',
  forceMessage:
    'There are some new features and updates. You must update the app',
  forcetxt1: 'Update now',
  forcetxt2: 'Maybe later',
  'Something Went wrong': 'Something went wrong',
  GM: 'GM',
  //Demo
  title1: 'Buy and sell in the Bookstores Market',
  desc1:
    'All types of paper and best prices in one place — save your time and money and start dealing directly with sellers.',
  title2: 'Explore offers',
  desc2: "Browse offers, compare prices, and choose what's best for you",
  title3: 'Track price movements',
  desc3: 'Monitor paper prices in the exchange and buy at the right time',
  title4: 'Display your products',
  desc4:
    'Display your products and start receiving orders from thousands of customers.',
  title5: 'Display your products',
  desc5:
    'Display your products and start receiving orders from thousands of customers.',
  //Addoffer
  addoffer1: 'Add paper offer',
  inkOfferTitle: 'Add inks offer',
  printerOfferTitle: 'Add printing press offer',
  editPaperOfferTitle: 'Edit paper offer',
  editInkOfferTitle: 'Edit inks offer',
  editPrinterOfferTitle: 'Edit printing press offer',
  categoriespopup: 'Choose the product type you want to sell',
  paperType: 'Paper Type*',
  paperTypew: 'Choose paper type',
  paperSize: 'Size*',
  paperSizew: 'Choose paper size',
  paperWight: 'Weight (grams)*',
  paperWightw: 'Enter paper weight',
  paperPrice: 'Price per carton*',
  paperPricew: 'Enter price per carton',
  papermintoorder: 'Minimum order quantity*',
  papermintoordew: 'Choose minimum order quantity',
  paperdis: 'Description',
  paperdisw: 'Enter product details, example: Maram paper 80g A4',
  paperDate: 'Offer end date',
  paperDatew: 'Offer expires automatically after 5 days',
  paperBranch: 'Branches',
  paperBranchw: 'Select available branches for the offer',
  paperDelivery: 'Is delivery available *',
  yes: 'Yes',
  no: 'No',
  addoffer: 'Add offer',
  lessOffer: 'Minimum order quantity',
  lessOfferw: 'Enter minimum order quantity',
  productImages: 'Product images',
  inkType: 'Ink type*',
  inkTypew: 'Choose ink type',
  inkBrand: 'Brand*',
  inkBrandw: 'Enter brand',
  inkCapacity: 'Capacity / volume (ml)*',
  inkCapacityw: 'Enter capacity or volume',
  inkColor: 'Color',
  inkColorw: 'Available colors (black, blue, etc.)',
  inkPriceUnit: 'Price (per cartridge or per liter)*',
  printerColorPrice: 'Color printing price *',
  printerColorPricew: 'Enter price',
  printerBWPrice: 'Black and white printing price *',
  printerBWPricew: 'Enter price',
  printingType: 'Printing type *',
  printingImmediate: 'Immediate printing',
  printingScheduled: 'Printing within time',
  //Menu items
  'The Account': 'Account',
  'My Orders': 'My Orders',
  'My Offers': 'My Offers',
  'Purchase Orders': 'Purchase Orders',
  Ratings: 'Ratings',
  'Favorite List': 'Favorite List',
  Branches: 'Branches',
  'Invite Friends': 'Invite Friends',
  'Change Password': 'Change Password',
  Reset: 'Reset',
  //OrderDetails
  orderDetailsTitle: 'Order Details',
  statusPending: 'Pending',
  statusAccepted: 'Order Accepted',
  statusCancelled: 'Order Cancelled',
  statusDelivered: 'Delivered',
  statusCompleted: 'Order Completed',
  statusNew: 'New Order',
  selectCancelReasons: 'Select cancellation reasons',
  writeCancelReasons: 'Write cancellation reasons',
  ratingSuccess: 'Rating submitted successfully',
  date: 'Date: ',
  quantity: 'Quantity: ',
  carton: 'carton',
  total: 'Total: ',
  pound: 'pounds',
  contactNow: 'Contact Now',
  delivered: 'Delivered',
  deliveryNote: 'If you received the order, press Delivered',
  accept: 'Accept',
  reject: 'Reject',
  cancelOrder: 'Cancel Order',
  rateSeller: 'Rate Seller',
  productDescription: 'Product Description',
  cancelReason: 'Cancellation reason:',
  type: 'Type',
  size: 'Size',
  weight: 'Weight',
  //RatingScreen
  rateSellerTitle: 'Rate Seller',
  rateBuyer: 'Rate Buyer',
  rateSellerSubtitle: 'Rate the seller',
  writeComment: 'Write your comment (optional)',
  rateExperience: 'Rate your experience',
  save: 'Save',
  //ProductDetails
  productDetailsTitle: 'Product Details',
  sellerInfo: 'Seller Information',
  selectQuantity: 'Select Quantity',
  minOrderQuantity: 'Minimum order quantity',
  offerEndDate: 'Offer end date:',
  orUntilOutOfStock: 'or until out of stock',
  deliveryMethods: 'Delivery methods:',
  deliveryAvailable: 'Delivery available',
  deliveryNotAvailable: 'Delivery not available',
  totalPrice: 'Total price:',
  excludingOtherFees: 'Excluding other fees',
  sendOrder: 'Send Order',
  orderSentSuccess: 'Your order has been sent successfully',
  alert: 'Alert',
  minQuantityAlert: 'Minimum quantity is',
  maxQuantityAlert: 'Maximum quantity is',
  //MyOrders
  myOrders: 'My Orders',
  all: 'All',
  //Notification
  requests: 'Orders',
  notifications: 'Notifications',
  //HomeMore
  price: 'Price',
  size: 'Size',
  paperTypeFilter: 'Paper Type',
  inkTypeFilter: 'Ink Type',
  governorate: 'Governorate',
  paperOffers: 'Paper Offers',
  chooseGovernorate: 'Choose governorate',
  choosePaperType: 'Choose paper type',
  choosePaperSize: 'Choose paper size',
  //Home2
  latestOffers: 'Latest offers',
  mainCategories: 'Main Categories',
  more: 'More',
  //Favorite
  favoriteList: 'Favorite List',
  offers: 'Offers',
  sellers: 'Sellers',
  specializedIn: 'Specialized in high-quality printing and writing paper',
  //SellerProfile
  sellerProfile: 'Seller Profile',
  edit: 'Edit',
  editOffer: 'Edit Offer',
  accountPublished: 'Account published as seller',
  ratingsCount: 'Ratings count',
  ordersCount: 'Orders count',
  offersCount: 'Offers count',
  accountInfo: 'Account Information',
  aboutCompany: 'About Company',
  companyTools: 'Company Services*',
  companyActivity: 'Company Activity',
  companyActivityw: 'Company Activity*',
  companyToolsw: 'Company Services',
  paymentMethods: 'Payment Methods',
  bankCard: 'Bank card (Visa / Mastercard)',
  electronicWallets: 'Electronic wallets (Vodafone Cash)',
  cashOnDelivery: 'Cash on Delivery',
  //UserProfile
  userName: 'Ahmed Mohamed',
  ordersCountText: 'Number of orders',
  ratingsCountText: 'Number of ratings',
  interestedMarkets: 'Markets of interest',
  paper: 'Paper',
  inks: 'Inks',
  printing: 'Printing',
  libraries: 'Libraries',
  supplyCompanies: 'Supply Companies',
  photocopyMachines: 'Photocopy Machines',
  officeSupplies: 'Office Supplies',
  cairo: 'Cairo',
  ainShams: 'Ain Shams',
  //Product Card
  viewDetails: 'View Details',
  productsCount: 'Products count',
  //CancelOrder
  confirmCancelOrder: 'Are you sure you want to cancel this order?',
  yesCancelOrder: 'Yes, cancel order',
  noGoBack: 'No, go back',
  //DeleteBranch
  cancelOrder: 'Delete Branch',
  confirmDeleteBranch: 'Are you sure you want to cancel this order?',
  yesDeleteBranch: 'Yes, cancel order',
  noGoBack: 'No, go back',
  //OrderCard
  governorateArea: 'Governorate - Area:',
  //MoreComponent
  library: 'Library',
  //SearchBar
  search: 'Search',
  carton_price: 'Carton price',
  select_branch: 'Select branch',
  select_price: 'Select price',
  carton: 'Carton',
  purchase_orders: 'Purchase orders',
  branches: 'branches',
  delete: 'Delete',
  branchCancle: 'Delete branch',
  confirmCancelBranch: 'Are you sure you want to cancel this branch?',
  yesCancelBranch: 'Yes, cancel branch',
  LogoutCancle: 'Logout confirmation',
  confirmLogout: 'Are you sure you want to log out?',
  yesLogout: 'Log out',
  confirmDeleteAccount: 'Are you sure you want to delete this account?',
  yesDelete: 'Yes, delete account',
  informations: 'informations',
  offer_details: 'offer details',
  delete_offer: 'delete offer',
  confirmCancelOffer: 'Are you sure you want to delete this offer?',
  yesCancelOffer: 'Yes, delete offer',
  seller_rate: 'Overall seller rating',
  product_number: 'Number of products:',
  logout: 'Logout',
  'Change Language': 'Change Language',
  'Rate App': 'Rate App',
  'RatePaper': 'Rate Paper',
  rated: 'Rated',
  terms: 'Terms',
  AboutAPP: 'About App',
  'Delete Account': 'Delete Account',
  'Account Info': 'Account Info',
  termsData:
    'Lorem Ipsum is simply dummy text (meaning the purpose is form, not content) and is used in the printing and publishing industries. Lorem Ipsum has been the standard dummy text since the 15th century, when an unknown printer took a galley of type and scrambled it to make a type specimen book. Five centuries have not eliminated this text; in fact, it has survived into electronic typesetting, remaining essentially unchanged. It became popular in the 1960s with the release of "Letraset" sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like "Aldus PageMaker" which also included versions of Lorem Ipsum.\nLorem Ipsum is simply dummy text (meaning the purpose is form, not content) and is used in the printing and publishing industries. Lorem Ipsum has been the standard dummy text since the 15th century, when an unknown printer took a galley of type and scrambled it to make a type specimen book. Five centuries have not eliminated this text; in fact, it has survived into electronic typesetting, remaining essentially unchanged. It became popular in the 1960s with the release of "Letraset" sheets containing Lorem Ipsum passages.',
  current_password: 'Current password',
  new_password: 'New password',
  confirm_new_password: 'Confirm new password',
  'countries is required': 'countries is required',
  'regions is required': 'regions is required',
  accountPublishedText: 'Account published as seller',
  offersCountText: 'Number of offers',
  ordersCountText: 'Number of orders',
  ratingsCountText: 'Number of ratings',
  AccountInfo: 'Account info',
  Rate: 'Your overall rating',
  latestInks: 'Latest inks offers',
  latestPrinting: 'Latest printing offers',
  offerInks: 'Inks offers',
  offerPrinters: 'Printers offers',
  interestedOffer: 'Offers that interest you',
  personalImage: 'Profile image',
  UpdateProfile: 'Edit profile',
  logoCompany: 'Company logo',
  DoneRate: 'Rated successfully',
  Success: 'Profile updated successfully',
  //AddOffer validation
  paperTypeRequired: 'Paper type is required',
  paperQuantityRequired: 'Quantity is required',
  paperDescriptionRequired: 'Description is required',
  branchesRequired: 'Branches are required',
  paperWeightRequired: 'Weight is required',
  paperSizeRequired: 'Size is required',
  paperPriceRequired: 'Price is required',
  inkTypeRequired: 'Ink type is required',
  brandRequired: 'Brand is required',
  colorRequired: 'Color is required',
  inkCapacityRequired: 'Capacity is required',
  imageRequired: 'Image is required',
  market: 'Market',
  Boursa: 'Boursa',
  NoData: 'No Data Available',
  NoDataDetails:
    'You need to log in to access this content and explore all features.',
};
